// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_fetch from "./routes/api/fetch.ts";
import * as $api_helper_HMAC from "./routes/api/helper/HMAC.ts";
import * as $api_helper_RSA_OAEP from "./routes/api/helper/RSA-OAEP.ts";
import * as $api_helper_RSASSA_PKCS1_v1_5 from "./routes/api/helper/RSASSA-PKCS1-v1_5.ts";
import * as $api_helper_cookie from "./routes/api/helper/cookie.ts";
import * as $api_helper_crypto from "./routes/api/helper/crypto.ts";
import * as $api_helper_date from "./routes/api/helper/date.ts";
import * as $api_helper_file from "./routes/api/helper/file.ts";
import * as $api_helper_puppeteer from "./routes/api/helper/puppeteer.ts";
import * as $api_helper_socket from "./routes/api/helper/socket.ts";
import * as $api_helper_whichCommond from "./routes/api/helper/whichCommond.ts";
import * as $api_info from "./routes/api/info.ts";
import * as $api_platforms_360_360 from "./routes/api/platforms/360/360.ts";
import * as $api_platforms_360_360_state from "./routes/api/platforms/360/360_state.ts";
import * as $api_platforms_360_path_ from "./routes/api/platforms/360/[path].tsx";
import * as $api_platforms_ali_path_ from "./routes/api/platforms/ali/[path].tsx";
import * as $api_platforms_ali_ali from "./routes/api/platforms/ali/ali.ts";
import * as $api_platforms_ali_ali_state from "./routes/api/platforms/ali/ali_state.ts";
import * as $api_platforms_baidu_path_ from "./routes/api/platforms/baidu/[path].tsx";
import * as $api_platforms_baidu_baidu from "./routes/api/platforms/baidu/baidu.ts";
import * as $api_platforms_baidu_baidu_state from "./routes/api/platforms/baidu/baidu_state.ts";
import * as $api_platforms_google_path_ from "./routes/api/platforms/google/[path].tsx";
import * as $api_platforms_google_google from "./routes/api/platforms/google/google.ts";
import * as $api_platforms_google_google_type from "./routes/api/platforms/google/google.type.ts";
import * as $api_platforms_google_google_state from "./routes/api/platforms/google/google_state.ts";
import * as $api_platforms_huawei_path_ from "./routes/api/platforms/huawei/[path].tsx";
import * as $api_platforms_huawei_huawei from "./routes/api/platforms/huawei/huawei.ts";
import * as $api_platforms_huawei_huawei_type from "./routes/api/platforms/huawei/huawei.type.ts";
import * as $api_platforms_huawei_huawei_state from "./routes/api/platforms/huawei/huawei_state.ts";
import * as $api_platforms_oppo_path_ from "./routes/api/platforms/oppo/[path].tsx";
import * as $api_platforms_oppo_oppo from "./routes/api/platforms/oppo/oppo.ts";
import * as $api_platforms_oppo_oppo_type from "./routes/api/platforms/oppo/oppo.type.ts";
import * as $api_platforms_oppo_oppo_state from "./routes/api/platforms/oppo/oppo_state.ts";
import * as $api_platforms_samsung_path_ from "./routes/api/platforms/samsung/[path].tsx";
import * as $api_platforms_samsung_samsung from "./routes/api/platforms/samsung/samsung.ts";
import * as $api_platforms_samsung_samsung_type from "./routes/api/platforms/samsung/samsung.type.ts";
import * as $api_platforms_samsung_samsung_state from "./routes/api/platforms/samsung/samsung_state.ts";
import * as $api_platforms_tencent_path_ from "./routes/api/platforms/tencent/[path].tsx";
import * as $api_platforms_tencent_tencent from "./routes/api/platforms/tencent/tencent.ts";
import * as $api_platforms_tencent_tencent_state from "./routes/api/platforms/tencent/tencent_state.ts";
import * as $api_platforms_vivo_path_ from "./routes/api/platforms/vivo/[path].tsx";
import * as $api_platforms_vivo_vivo from "./routes/api/platforms/vivo/vivo.ts";
import * as $api_platforms_vivo_vivo_type from "./routes/api/platforms/vivo/vivo.type.ts";
import * as $api_platforms_vivo_vivo_state from "./routes/api/platforms/vivo/vivo_state.ts";
import * as $api_platforms_xiaomi_path_ from "./routes/api/platforms/xiaomi/[path].tsx";
import * as $api_platforms_xiaomi_xiaomi from "./routes/api/platforms/xiaomi/xiaomi.ts";
import * as $api_platforms_xiaomi_xiaomi_type from "./routes/api/platforms/xiaomi/xiaomi.type.ts";
import * as $api_platforms_xiaomi_xiaomi_state from "./routes/api/platforms/xiaomi/xiaomi_state.ts";
import * as $api_setting_app from "./routes/api/setting/app.ts";
import * as $api_setting_handle_key_ from "./routes/api/setting/handle/[key].tsx";
import * as $api_setting_handle_index from "./routes/api/setting/handle/index.tsx";
import * as $api_setting_index from "./routes/api/setting/index.tsx";
import * as $api_setting_metadata_key_ from "./routes/api/setting/metadata/[key].tsx";
import * as $api_setting_metadata_index from "./routes/api/setting/metadata/index.tsx";
import * as $api_setting_resource_key_ from "./routes/api/setting/resource/[key].tsx";
import * as $api_setting_resource_index from "./routes/api/setting/resource/index.tsx";
import * as $api_setting_screenshot_key_ from "./routes/api/setting/screenshot/[key].tsx";
import * as $api_setting_screenshot_index from "./routes/api/setting/screenshot/index.tsx";
import * as $api_state_path_ from "./routes/api/state/[path].tsx";
import * as $api_update from "./routes/api/update.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $partials_google from "./routes/partials/google.tsx";
import * as $partials_huawei from "./routes/partials/huawei.tsx";
import * as $partials_key from "./routes/partials/key.tsx";
import * as $partials_oppo from "./routes/partials/oppo.tsx";
import * as $partials_samsung from "./routes/partials/samsung.tsx";
import * as $partials_semi from "./routes/partials/semi.tsx";
import * as $partials_setting from "./routes/partials/setting.tsx";
import * as $partials_state from "./routes/partials/state.tsx";
import * as $partials_vivo from "./routes/partials/vivo.tsx";
import * as $partials_xiaomi from "./routes/partials/xiaomi.tsx";
import * as $publish_HandleRender from "./islands/publish/HandleRender.tsx";
import * as $publish_messageRender from "./islands/publish/messageRender.tsx";
import * as $semi_PublishButton from "./islands/semi/PublishButton.tsx";
import * as $semi_toast from "./islands/semi/toast.tsx";
import * as $setting_ApkRender from "./islands/setting/ApkRender.tsx";
import * as $setting_HandleRender from "./islands/setting/HandleRender.tsx";
import * as $setting_InfoRender from "./islands/setting/InfoRender.tsx";
import * as $setting_ScreenshotsRender from "./islands/setting/ScreenshotsRender.tsx";
import * as $setting_TextRender from "./islands/setting/TextRender.tsx";
import * as $setting_submitRender from "./islands/setting/submitRender.tsx";
import * as $state_List from "./islands/state/List.tsx";
import * as $state_ReloadButton from "./islands/state/ReloadButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/fetch.ts": $api_fetch,
    "./routes/api/helper/HMAC.ts": $api_helper_HMAC,
    "./routes/api/helper/RSA-OAEP.ts": $api_helper_RSA_OAEP,
    "./routes/api/helper/RSASSA-PKCS1-v1_5.ts": $api_helper_RSASSA_PKCS1_v1_5,
    "./routes/api/helper/cookie.ts": $api_helper_cookie,
    "./routes/api/helper/crypto.ts": $api_helper_crypto,
    "./routes/api/helper/date.ts": $api_helper_date,
    "./routes/api/helper/file.ts": $api_helper_file,
    "./routes/api/helper/puppeteer.ts": $api_helper_puppeteer,
    "./routes/api/helper/socket.ts": $api_helper_socket,
    "./routes/api/helper/whichCommond.ts": $api_helper_whichCommond,
    "./routes/api/info.ts": $api_info,
    "./routes/api/platforms/360/360.ts": $api_platforms_360_360,
    "./routes/api/platforms/360/360_state.ts": $api_platforms_360_360_state,
    "./routes/api/platforms/360/[path].tsx": $api_platforms_360_path_,
    "./routes/api/platforms/ali/[path].tsx": $api_platforms_ali_path_,
    "./routes/api/platforms/ali/ali.ts": $api_platforms_ali_ali,
    "./routes/api/platforms/ali/ali_state.ts": $api_platforms_ali_ali_state,
    "./routes/api/platforms/baidu/[path].tsx": $api_platforms_baidu_path_,
    "./routes/api/platforms/baidu/baidu.ts": $api_platforms_baidu_baidu,
    "./routes/api/platforms/baidu/baidu_state.ts":
      $api_platforms_baidu_baidu_state,
    "./routes/api/platforms/google/[path].tsx": $api_platforms_google_path_,
    "./routes/api/platforms/google/google.ts": $api_platforms_google_google,
    "./routes/api/platforms/google/google.type.ts":
      $api_platforms_google_google_type,
    "./routes/api/platforms/google/google_state.ts":
      $api_platforms_google_google_state,
    "./routes/api/platforms/huawei/[path].tsx": $api_platforms_huawei_path_,
    "./routes/api/platforms/huawei/huawei.ts": $api_platforms_huawei_huawei,
    "./routes/api/platforms/huawei/huawei.type.ts":
      $api_platforms_huawei_huawei_type,
    "./routes/api/platforms/huawei/huawei_state.ts":
      $api_platforms_huawei_huawei_state,
    "./routes/api/platforms/oppo/[path].tsx": $api_platforms_oppo_path_,
    "./routes/api/platforms/oppo/oppo.ts": $api_platforms_oppo_oppo,
    "./routes/api/platforms/oppo/oppo.type.ts": $api_platforms_oppo_oppo_type,
    "./routes/api/platforms/oppo/oppo_state.ts": $api_platforms_oppo_oppo_state,
    "./routes/api/platforms/samsung/[path].tsx": $api_platforms_samsung_path_,
    "./routes/api/platforms/samsung/samsung.ts": $api_platforms_samsung_samsung,
    "./routes/api/platforms/samsung/samsung.type.ts":
      $api_platforms_samsung_samsung_type,
    "./routes/api/platforms/samsung/samsung_state.ts":
      $api_platforms_samsung_samsung_state,
    "./routes/api/platforms/tencent/[path].tsx": $api_platforms_tencent_path_,
    "./routes/api/platforms/tencent/tencent.ts": $api_platforms_tencent_tencent,
    "./routes/api/platforms/tencent/tencent_state.ts":
      $api_platforms_tencent_tencent_state,
    "./routes/api/platforms/vivo/[path].tsx": $api_platforms_vivo_path_,
    "./routes/api/platforms/vivo/vivo.ts": $api_platforms_vivo_vivo,
    "./routes/api/platforms/vivo/vivo.type.ts": $api_platforms_vivo_vivo_type,
    "./routes/api/platforms/vivo/vivo_state.ts": $api_platforms_vivo_vivo_state,
    "./routes/api/platforms/xiaomi/[path].tsx": $api_platforms_xiaomi_path_,
    "./routes/api/platforms/xiaomi/xiaomi.ts": $api_platforms_xiaomi_xiaomi,
    "./routes/api/platforms/xiaomi/xiaomi.type.ts":
      $api_platforms_xiaomi_xiaomi_type,
    "./routes/api/platforms/xiaomi/xiaomi_state.ts":
      $api_platforms_xiaomi_xiaomi_state,
    "./routes/api/setting/app.ts": $api_setting_app,
    "./routes/api/setting/handle/[key].tsx": $api_setting_handle_key_,
    "./routes/api/setting/handle/index.tsx": $api_setting_handle_index,
    "./routes/api/setting/index.tsx": $api_setting_index,
    "./routes/api/setting/metadata/[key].tsx": $api_setting_metadata_key_,
    "./routes/api/setting/metadata/index.tsx": $api_setting_metadata_index,
    "./routes/api/setting/resource/[key].tsx": $api_setting_resource_key_,
    "./routes/api/setting/resource/index.tsx": $api_setting_resource_index,
    "./routes/api/setting/screenshot/[key].tsx": $api_setting_screenshot_key_,
    "./routes/api/setting/screenshot/index.tsx": $api_setting_screenshot_index,
    "./routes/api/state/[path].tsx": $api_state_path_,
    "./routes/api/update.ts": $api_update,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/partials/google.tsx": $partials_google,
    "./routes/partials/huawei.tsx": $partials_huawei,
    "./routes/partials/key.tsx": $partials_key,
    "./routes/partials/oppo.tsx": $partials_oppo,
    "./routes/partials/samsung.tsx": $partials_samsung,
    "./routes/partials/semi.tsx": $partials_semi,
    "./routes/partials/setting.tsx": $partials_setting,
    "./routes/partials/state.tsx": $partials_state,
    "./routes/partials/vivo.tsx": $partials_vivo,
    "./routes/partials/xiaomi.tsx": $partials_xiaomi,
  },
  islands: {
    "./islands/publish/HandleRender.tsx": $publish_HandleRender,
    "./islands/publish/messageRender.tsx": $publish_messageRender,
    "./islands/semi/PublishButton.tsx": $semi_PublishButton,
    "./islands/semi/toast.tsx": $semi_toast,
    "./islands/setting/ApkRender.tsx": $setting_ApkRender,
    "./islands/setting/HandleRender.tsx": $setting_HandleRender,
    "./islands/setting/InfoRender.tsx": $setting_InfoRender,
    "./islands/setting/ScreenshotsRender.tsx": $setting_ScreenshotsRender,
    "./islands/setting/TextRender.tsx": $setting_TextRender,
    "./islands/setting/submitRender.tsx": $setting_submitRender,
    "./islands/state/List.tsx": $state_List,
    "./islands/state/ReloadButton.tsx": $state_ReloadButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
